travis:
  secure:
    BINSTAR_TOKEN: STwgtwfPhhSwVhQZ2UeGxHP0Kr2fCL8luCrnu0DO4kJUADYfJveaZEuYTFClwF2Dm/o4xpvHH2D44Hkb5IZIlpe/o99gzqqcWivLTB0hgCKZFlrMwBALmcmcQv4UwDZK82IKDiYQCbn6vJJYdxsMfLKmZMH9hxNHE8K9iO9jSRJCIbBkaSsELovlVrPCH8m1qqbQ7eGL5CdAamG9poEJ5Gy+dwkiIAlpXloh7QDzlOkuN9KX8rttXxRUXzzRtkBb9kqDBulX7wiBTvYT12/zo6VWLdCgrjDB5a1Gr8aGDCpQslQza5TCx3P/wRY+kegzeqYVEelYD2M7sCe4VSkkyU5HCyeQddifqd5zRMJWoa5wtuRriRzee4EwyjED5cwua4Qs0ZW9wQauEzTIvwZjm47RljNPvGTlyfzeoqlGer0UpDmd6wADaT4gXiFPQhfyfQ3G/uR3m2C8+0qUK0ykW8Cb0VJFv04hBYYzUOWMrG7NpLs8XXsWiv83NMWr91wTafv5ecZ6ZA94bIrj8fR6JuAycVZ9Viv3Lgt4J3ctO+P6EInTpSrZVeyG3ZI9naJ8K+fAZ5tSXiCKhDf4DyBISKtL6R6xKag+VkQe/N38akbHLjjXFGQOdLEYuD2YWj3ACnsZ85RNQJvLvlFdywPZf5j2dwzJLhRr6UNfzilxclE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
