travis:
  secure:
    BINSTAR_TOKEN: xmvxQ9uNXKNQGJwWADDsn0UlL2cVzJflgipG7yyQ3T2xGMMWIoqCitGMABeDE69wF+yK7aYTrP459wLfqdz5x5cwDWU3TKTRKNMz4U4ZCwEV3hbG0yrRoMLzgSXSONYAY5Vbl37QpUOAfW5JuWtHvyXQc7UFSo8LghnGlo1OCstmrq0UpSJaJaWXVePIq4pioJjvuQ7wC64NcOtjXBbx87P/oFcHNWCEU0Y2+XIcR2s48JoTKArZJQ+iQN4E557p4/yLCT7irowPIFthscnIBQEtuDJ+mNNSZQDdo6VRq517lXgOrMp226A341JNbqySnoeo5Qnx0+JqzUQKGSNCADPVt5G5s1Mn4mcnkJtPSLp4luGqpGIF5NJjYT1L1hC/0iLCtDihoPjn/ZjJxLlnqircLPreq80cjQYKs0aziFAggREyux6T432msks+N/TBZxxa8SrQ2N5i4Kz3lt6NCthb3q6CqBmO7qg15uIGYtp/EyMf3x0H9DAh6jiWVJau8Hhv20qRrciBs3CGy7r2pr2Ow5MCpGqvDvDiLJIXE9nG2Fc3i2ChLzpr2EOZntEuWj3xzD64fuQOrPqZkDjlVnNH6zfthpelUJevOrjLtZKqgVMO910cs7VomTgTQ6Bn4u7xfvdgUbnoys1OOrPeV1ozvVpF29Jjxav90mTheh4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
